config/routes.rb
SEPersonalWeb::Application.routes.draw do

  get "routines/create"

  get "routines/destroy"

  root :to => 'pages#home'

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :routines

  resources :videos do
    member do
      post :add_comment
    end
    new do
       post :upload
       get  :save_video
     end
  end

  match "videos/:id/add_comment", :to => "videos#add_comment"
  match "videoclass" , :to =>"videos#index"
  match '/home', :to => 'pages#home'
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/dance', :to => 'dance#index'
  match '/delete', :to => 'routine#destroy'

end

app/models/video.rb
class Video < ActiveRecord::Base
  acts_as_commentable
  
  attr_accessor :comment
  
  scope :completes,   where(:is_complete => true)
  scope :incompletes, where(:is_complete => false)
  
  def create_comment(comment)
    begin
      comments.create(:comment => comment)
      Video.yt_session.add_comment(yt_video_id, comment)
    rescue
      false
    end
  end
  
    
  def self.yt_session
    @yt_session ||= YouTubeIt::Client.new(:username => YouTubeITConfig.username , :password => YouTubeITConfig.password , :dev_key => YouTubeITConfig.dev_key)    
  end

  def self.delete_video(video)
    yt_session.video_delete(video.yt_video_id)
    video.destroy
      rescue
        video.destroy
  end

  def self.update_video(video, params)
    yt_session.video_update(video.yt_video_id, video_options(params))
    video.update_attributes(params)
  end

  def self.token_form(params, nexturl)
    yt_session.upload_token(video_options(params), nexturl)
  end

  def self.delete_incomplete_videos
    self.incompletes.map{|r| r.destroy}
  end

  private
    def self.video_options(params)
      opts = {:title => params[:title],
             :description => params[:description],
             :category => "People",
             :keywords => ["test"]}
      params[:is_unpublished] == "1" ? opts.merge(:private => "true") : opts
    end
end

app/controllers/videos_controller.rb
class VideosController < InheritedResources::Base

  def upload
    @video = Video.create(params[:video])
    if @video
      @upload_info = Video.token_form(params[:video], save_video_new_video_url(:video_id => @video.id))
    else
      respond_to do |format|
        format.html { render "/videos/new" }
      end
    end
  end

  def update
    @video     = Video.find(params[:id])
    @result    = Video.update_video(@video, params[:video])
    respond_to do |format|
      format.html do
        if @result
          redirect_to @video, :notice => "video successfully updated"
        else
          respond_to do |format|
            format.html { render "/videos/_edit" }
          end
        end
      end
    end
  end

  def save_video
    @video = Video.find(params[:video_id])
    if params[:status].to_i == 200
      @video.update_attributes(:yt_video_id => params[:id].to_s, :is_complete => true)
      Video.delete_incomplete_videos
    else
      Video.delete_video(@video)
    end
    redirect_to videos_path, :notice => "video successfully uploaded"
  end

  def destroy
    @video = Video.find(params[:id])
    if Video.delete_video(@video)
      flash[:notice] = "video successfully deleted"
    else
      flash[:error] = "video unsuccessfully deleted"
    end
    redirect_to videos_path
  end

  def add_comment
    @video = Video.find(params[:id])
    if @video.create_comment(params[:video][:comment])
      flash[:notice] = "Comment has been sucessfully added."
    else
      flash[:error] = "Sorry the comment has not been added."
    end
    redirect_to @video    
  end

  protected
    def collection
      @videos ||= end_of_association_chain.completes
    end

end

app/views/videos/_form.html.erb
  <div class="group">
    <%= f.label :title, t("activerecord.attributes.video.title", :default => "Title"), :class => :label %>
    <%= f.text_field :title, :class => 'text_field' %>
    <span class="description">Ex: add title video</span>
  </div>

  <div class="group">
    <%= f.label :description, t("activerecord.attributes.video.description", :default => "Description"), :class => :label %>
    <%= f.text_field :description, :class => 'text_field' %>
    <span class="description">Ex: add description video</span>
  </div>

<div class="group navform wat-cf">
<% if @video.new_record?%>
  <button class="button" type="submit">
    <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}") %> <%= t("web-app-theme.save", :default => "Step 2") %>
  </button>
<%else%>
  <button class="button" type="submit">
    <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}") %> <%= t("web-app-theme.save", :default => "Save") %>
  </button>
<%end%>

  <span class="text_button_padding"><%= t("web-app-theme.or", :default => "or") %></span>
	<%= link_to t("web-app-theme.cancel", :default => "Cancel"), videos_path, :class => "text_button_padding link_button" %>
</div>

app/views/videos/_sidebar.html.erb
<div class="block notice">
  <h3>YouTube IT Demo</h3>
  <p>Using youtube_it gem you can do:</p>
  <div class="content">
    <p>Upload your video to YouTube from here!.</p>
    <p>Add, Delete, Update videos from here and see the changes on YouTube site.</p>
    <p>Add comments to yours videos.</p>
  </div>
</div>

app/views/videos/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", videos_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_video_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_video_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> Video</h2>
    <div class="inner">
      <%= form_for @video, :url => video_path(@video), :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/videos/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.list", :default => "List")}", videos_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_video_path %></li>
    </ul>
  </div>          
  <div class="content">          
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Videos</h2>
    <div class="inner">
      <table class="table">
        <tr>             
          <th class="first">ID</th>
                    <th>
            <%= t("activerecord.attributes.video.title", :default => t("activerecord.labels.title", :default => "Title")) %>
          </th>
                    <th><%= t("web-app-theme.created_at", :default => "Created at")  %></th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @videos.each do |video| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= video.id %>
          </td>
                    <td>
            <%= link_to video.title, video_path(video) %>
          </td>
                    <td>
            <%= video.created_at %>
          </td>
          <td class="last">
            <%= link_to "#{t("web-app-theme.show", :default => "Show")}", video_path(video) %> |
            <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_video_path(video) %> |
            <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", video_path(video), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
          </td>
        </tr>          
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/videos/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", videos_path  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_video_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  Video</h2>
    <div class="inner">
      <p>Step 1: add information about your video.</p>
      <%= form_for @video, :url => upload_new_video_path, :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/videos/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", videos_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_video_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.show", :default => "Show")}", video_path %></li>
    </ul>
  </div>          
  <div class="content">
    <div class="inner">
      
        <p>
          <%= raw yt_client.my_video(@video.yt_video_id).embed_html %>
        </p>
        <h3><%= @video.description %></h3>
        <p><b>url:</b> <a href="http://www.youtube.com/watch?v=<%= @video.yt_video_id %>&feature=youtube_it" target="_blank">http://www.youtube.com/watch?v=<%= @video.yt_video_id %></a></p>

      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_video_path(@video), :class => "button" %> 
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), video_path(@video), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>      
    </div>
  </div>
  <h2>Comments:</h2>
  <div class="inner">
    <ul class="list">        
      <% @video.comments.each do |c| %>
        <li>
          <div class="item" style="margin-left: 8px !important;">
            <p><%= c.comment %></p>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
    <br/><br/>
  <%= form_for @video, :url => add_comment_video_path(@video), :html => { :class => :form } do |f| -%>
  <div class="group">
    <%= f.label :comment, "Add your comment", :class => :label %>
    <%= f.text_area :comment, :class => 'text_area', :rows => 10 %>
  </div>
  <%= f.submit "add comment"%>
  <% end -%>
<br/><br/>

</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/videos/upload.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", videos_path  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_video_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  Video</h2>
    <div class="inner">
      <p>Step 2: upload a new video.</p>

      <%= form_tag @upload_info[:url], :multipart => true do %>
        <%= hidden_field_tag :token, @upload_info[:token] %>
        <%= label_tag :file %>
        <%= file_field_tag :file %>
        <%= submit_tag "Upload video" %>
      <% end %>    
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>