config/routes.rb
SEPersonalWeb::Application.routes.draw do

  get "routines/create"

  get "routines/destroy"

  root :to => 'pages#home'

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :routines

  resources :videos do
    member do
      post :add_comment
    end
    new do
       post :upload
       get  :save_video
     end
  end

  match "videos/:id/add_comment", :to => "videos#add_comment"
  match "videoclass" , :to =>"videos#index"
  match '/home', :to => 'pages#home'
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/dance', :to => 'dance#index'
  match '/delete', :to => 'routine#destroy'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dance Teaching Room >> <%= @title %></title>
  <%= stylesheet_link_tag "web-app-theme/base", "web-app-theme/override" %>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<div class="container">
      <header>
        <%= image_tag("logo.png", :alt => "dance teaching room", :class => "round") %>
        <nav class="round">
          <ul>
            <li><%= link_to "Home", home_path %></li>
            <li><%= link_to "Waltz Steps", dance_path %></li>
            <% if signed_in? %>
                <li><%= link_to current_user.name+'\'s Routine' , current_user %></li>
                <li><%= link_to "Video Class", videoclass_path %></li>
                <li><%= link_to "Log out", signout_path %></li>
            <% end %>
          </ul>
        </nav>
      </header>
      <section class="round">
        <% flash.each do |key, value| %>
          <div style="color: red" class="flash <%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
      </section>
    </div>

</body>
</html>